android/build.gradle
android/src/main/java/com/instabug/instabugflutter/ArgsRegistry.java
android/src/main/java/com/instabug/instabugflutter/InstabugFlutterPlugin.java
android/src/test/java/com/instabug/instabugflutter/ArgsRegistryTest.java
lib/instabug_flutter.dart

Converted the `InstabugFlutterPlugin.getConstants()` to a registry for easier code maintenance and unit testing.
- Modified `Instabug-Flutter/android/build.gradle` (added [junit4](https://junit.org/junit4/) dependency)
- Added `ArgsRegistry`
- Added `ArgsRegistryTest`
- Modified `InstabugFlutterPlugin` (Removed unused imports, replaced deprecated API and replaced all `getConstants()` calls with `ArgsRegistry`)
- Reformatted code [`InstabugFlutterPlugin` & `ArgsRegistry`]
- Added missing languages [`PortuguesePortugal`, `Indonesian`, `Slovak` and `Norwegian`]

Enhance constants lookup and add unit testing

---

.circleci/config.yml

For now, treats all warnings as errors, until we figure out which of them we actually care about.

Treats lint warnings as errors

---

CHANGELOG.md
README.md
android/src/main/java/com/instabug/instabugflutter/InstabugFlutterPlugin.java
example/lib/main.dart
ios/Classes/InstabugFlutterPlugin.m
lib/Instabug.dart
test/instabug_flutter_test.dart

1) Android API Mapping
2) IOS API Mapping
3) Flutter API Mapping
4) Adds tests for new API
5) updates Readme
6) updated Changelog

[Mob 3186] - Flutter API: tintColor

---

CHANGELOG.md
README.md
android/src/main/java/com/instabug/instabugflutter/InstabugFlutterPlugin.java
example/lib/main.dart
ios/Classes/InstabugFlutterPlugin.m
lib/BugReporting.dart
test/instabug_flutter_test.dart

* setOnDismissCallback
* setOnInvokeCallback
* BugReporting.setEnabled

[Mob 3193] - [Mob 3195]

---

CHANGELOG.md
README.md
android/src/main/java/com/instabug/instabugflutter/ArgsRegistry.java
android/src/main/java/com/instabug/instabugflutter/InstabugFlutterPlugin.java
example/lib/main.dart
ios/Classes/InstabugFlutterPlugin.m
lib/Chats.dart
lib/FeatureRequests.dart
test/instabug_flutter_test.dart

* Android API & Enums Mappings
* IOS API & Enums Mapping
* showFeatureRequests
* setEmailFieldRequiredForFeatureRequests
* showChats
* setChatsEnabled

[Mob 3372] , [MOB-3377], [Mob 3382] , [MOB-3387]: Flutter API [FeatureRequests], [Chats]

---

CHANGELOG.md
android/src/main/java/com/instabug/instabugflutter/ArgsRegistry.java
android/src/test/java/com/instabug/instabugflutter/ArgsRegistryTest.java
ios/Classes/InstabugFlutterPlugin.m
lib/Instabug.dart

Added enum `CustomTextPlaceHolderKey.reportQuestion` which maps to `InstabugCustomTextPlaceHolder.Key.REPORT_QUESTION` on Android and `kIBGAskAQuestionStringName` on iOS.

Add reportQuestion enum

---

CHANGELOG.md
android/src/main/java/com/instabug/instabugflutter/InstabugFlutterPlugin.java
ios/Classes/InstabugFlutterPlugin.m
lib/BugReporting.dart

* Adds `setShakingThresholdForiPhone`, `setShakingThresholdForiPad` and `setShakingThresholdForAndroid` APIs
* Fixes #125

Feature - Add shaking threshold APIs

---

CHANGELOG.md
ios/Classes/InstabugFlutterPlugin.m

Fixes an issue with iOS invocation events causing the welcome message not to show.

Fix iOS initial invocation events

---

.gitignore

Adds .flutter-plugins-dependencies to .gitignore

Add .flutter-plugins-dependencies to .gitignore

---

lib/InstabugNavigatorObserver.dart

Fixed Case: 
1) You stay on first sceen in app 
2) Call `Navigator.pushNamedAndRemoveUntil`
3) Have nullable previosPage

Fixed NPE in Observer when we don't have previous page

---

.circleci/config.yml
InstabugSample/ios/Podfile.lock
InstabugSample/pubspec.yaml
README.md
codecov.yml

- Updated Instabug version in the sample app's lock file, this should fix the iOS CI.
- Updated SDK path in the sample app.
- Temporarily disabled failing Android UI tests till a native fix is released (expected within the next week).
- Reformated CrashReporting integration steps to state the recommended steps before the deprecated ones.
- Added codcov config.

[MOB-4957] Fix failing CI on master

---

android/src/main/java/com/instabug/instabugflutter/InstabugFlutterPlugin.java
example/android/app/src/main/kotlin/com/example/InstabugSample/OnMethodCallTests.java
example/android/app/src/test/java/com/example/InstabugSample/InstabugFlutterPluginTest.java
lib/Instabug.dart
test/instabug_flutter_test.dart

- Added setDebugEnabled API to enable/disable the Instabug debug logs.
- API added for Android only
- Unit test added to java test files only

[MOB-4686] Feature/add setDebugEnabled Android API

---

ios/Classes/InstabugFlutterPlugin.h
ios/Classes/InstabugFlutterPlugin.m
lib/Instabug.dart
test/instabug_flutter_test.dart

Added setSdkDebugLogsLevel iOS API.

Feature/Add setSdkDebugLogsLevel iOS API

---

CHANGELOG.md
analysis_options.yaml
example/ios/InstabugSampleTests/InstabugSampleTests.m
ios/Classes/InstabugFlutterPlugin.h
ios/Classes/InstabugFlutterPlugin.m
lib/APM.dart
lib/CrashReporting.dart
lib/Instabug.dart
test/instabug_flutter_test.dart

* Fix future dart calls for void methods on iOS.  (Thanks to @via-guy)
* Fix & Improve iOS unit tests.

[MOB-8369] Fix `void` calls on iOS

---

CHANGELOG.md
android/src/main/java/com/instabug/instabugflutter/InstabugFlutterPlugin.java
example/android/app/src/main/kotlin/com/example/InstabugSample/OnMethodCallTests.java
example/android/app/src/test/java/com/example/InstabugSample/InstabugFlutterPluginTest.java
example/ios/InstabugSampleTests/InstabugSampleTests.m
ios/Classes/InstabugFlutterPlugin.h
ios/Classes/InstabugFlutterPlugin.m
lib/Instabug.dart
test/instabug_flutter_test.dart

Add Experiments APIs: `addExperiments`, `removeExperiments`, `clearAllExperiments`.

[MOB-8360] Add Expirements APIs

---

android/build.gradle
android/src/main/java/com/instabug/instabugflutter/ArgsRegistry.java
android/src/test/java/com/instabug/instabugflutter/ArgsRegistryTest.java
ios/Classes/InstabugFlutterPlugin.m
ios/instabug_flutter.podspec
lib/Instabug.dart

- Bump iOS SDK to v11.0.2
- Bump Android SDK to v11.2.0
- Remove the string keys `bugReportHeader` and `feedbackReportHeader`. Use `reportBug` and `reportFeedback` as an alternative
- Update `Surveys.hasRespondedToSurvey` implementation on iOS

[MOB-8893] Bump Native SDKs to v11

---

CHANGELOG.md
android/src/main/java/com/instabug/instabugflutter/InstabugFlutterPlugin.java
example/android/app/src/androidTest/java/com/example/InstabugSample/InvokeInstabugUITest.java

- Call media projection method directly instead of by reflection. (#232)

[MOB-8741] Direct call for media projection method

---

.circleci/config.yml

- Bumps xcode version to v13.4.1 for `ios_tests` job
- Bumps xcode version to v13.4.1 for `android_tests` job
- Bumps xcode version to v13.4.1 for `gh_ibg_release` job

[MOB-9109] Bump deprecated Xcode versions for affected CI jobs

---

.circleci/config.yml

- Remove `HOMEBREW_NO_AUTO_UPDATE` flag to fix failing `android_tests` job

[MOB-9669] Allow brew Auto Update

---

CHANGELOG.md
ios/Classes/InstabugFlutterPlugin.m

`BugReporting.setInvocationEvents` used to always set the invocation events to **none** due to wrong initialization value.

[MOB-9934] Fix `BugReporting.setInvocationEvents`

---

lib/src/modules/instabug.dart
test/instabug_flutter_test.dart

- Ignore `unnecessary_import` lint rule on specific imports that are no longer needed due to the used elements being provided by the import of `package:flutter/services.dart` on Flutter 3.3
- These imports weren't removed so that the package maintains supported versions prior to Flutter 3.3

[MOB-9967] Fix Lint Issue on Flutter 3.3

---

.circleci/config.yml

Migrates Android test job to use both Android and Flutter orbs.

[MOB-10003] Migrate Android CI Job to Orbs

---

example/ios/Runner/Info.plist

On iOS, the example app crashes if you try to use video recording in bug reporting attachments as the app doesn't specify the microphone usage description (used when the app asks for permission) in the `Info.plist` file.
Same for attaching photos from the gallery, the feature wouldn't work because of the missing permission.
I added the microphone (`NSMicrophoneUsageDescription`) and photo library (`NSPhotoLibraryUsageDescription`) usage description to the example app's iOS `Info.plist`.

[MOB-10037] Add missing iOS permission in example app

---

CHANGELOG.md
android/src/main/java/com/instabug/flutter/ArgsRegistry.java
android/src/main/java/com/instabug/flutter/InstabugFlutterPlugin.java
example/android/app/src/main/kotlin/com/example/InstabugSample/OnMethodCallTests.java
example/android/app/src/test/java/com/example/InstabugSample/InstabugFlutterPluginTest.java
example/ios/InstabugSampleTests/InstabugSampleTests.m
ios/Classes/InstabugFlutterPlugin.h
ios/Classes/InstabugFlutterPlugin.m
lib/src/modules/bug_reporting.dart
test/instabug_flutter_test.dart

- Add `BugReporting.setVideoRecordingFloatingButtonPosition` API

[IBGCORE-17136] Add `BugReporting.setVideoRecordingFloatingButtonPosition` API

---

CHANGELOG.md
android/src/main/java/com/instabug/flutter/ArgsRegistry.java
android/src/main/java/com/instabug/flutter/InstabugFlutterPlugin.java
android/src/test/java/com/instabug/flutter/ArgsRegistryTest.java

We have an issue with some string keys not working on Android. The reason is that for these keys, `getDeserializedValue` returns `null` due to the expression `constant.getClass().isAssignableFrom(clazz)` evaluating to `false`. This happens with the keys having `charLimit` method overridden on the native side. 
Remove Class parameter in `getDeserializedValue` method and its check

[MOB-10329] Fix non-working String Keys on Android

---

example/android/app/src/androidTest/java/com/example/InstabugSample/InvokeInstabugUITest.java

- Remove unused `getMethod` in Android UI tests

[MOB-10300] Remove unused code in Android UI tests

---

.circleci/config.yml

Create a parameterized job for Flutter tests for testing  on both versions `v2` and `stable`.

[MOB-10537] Merge `test_flutter` CI Jobs Together

---

.circleci/config.yml

Installing latest version of .NET using `brew` caused `e2e_ios_captain` job to **fail**, since it was designed based on .NET 6 and `brew` only fetches the latest version.
This PR uses `isen-ng/homebrew-dotnet-sdk-versions` to install .NET 6 instead of latest version.

[MOB-10569] Pin CI .NET Version to 6

---

CHANGELOG.md
android/src/main/java/com/instabug/flutter/modules/ApmApi.java
android/src/main/java/com/instabug/flutter/modules/BugReportingApi.java
android/src/main/java/com/instabug/flutter/modules/CrashReportingApi.java
android/src/main/java/com/instabug/flutter/modules/InstabugApi.java
android/src/main/java/com/instabug/flutter/modules/RepliesApi.java
android/src/main/java/com/instabug/flutter/modules/SurveysApi.java
android/src/main/java/com/instabug/flutter/util/ThreadManager.java
ios/Classes/Modules/ApmApi.m
ios/Classes/Modules/InstabugApi.m
ios/Classes/Modules/RepliesApi.m
pigeons/apm.api.dart
pigeons/instabug.api.dart
pigeons/replies.api.dart

1. Remove main thread wrappers from Android, since [Flutter plugin methods run by default on main thread](https://docs.flutter.dev/development/platform-integration/platform-channels#channels-and-platform-threading).
1. Run Android non-void APIs on background thread, to fix threading violation reported by Instabug Android SDK.

[MOB-9125] Fix Main Thread Violation

---

.circleci/config.yml

Install .NET 6 using Microsoft's `dotnet-install.sh` script.

[MOB-10721] Install .NET 6 using Shell Script

---

CHANGELOG.md
lib/src/modules/replies.dart
lib/src/modules/surveys.dart
test/replies_test.dart
test/surveys_test.dart

Some APIs had a callback function which was used to return values of the asynchronous calls. This behaviour was replaced by a return value instead.
```dart
// The old callback way (deprecated)
Replies.hasChats((result) => print(result));
// The new return value way
final result = Replies.hasChats();
print(result);
```
1. `Replies.getUnreadRepliesCount`
2. `Replies.hasChats`
3. `Surveys.hasRespondedToSurvey`
4. `Surveys.getAvailableSurveys`

[MOB-10548] Use Return Values Instead of Callbacks

---

CHANGELOG.md
android/src/main/java/com/instabug/flutter/modules/BugReportingApi.java
android/src/main/java/com/instabug/flutter/modules/InstabugApi.java
ios/Classes/Modules/BugReportingApi.m
ios/Classes/Modules/InstabugApi.m
lib/src/modules/bug_reporting.dart
lib/src/modules/instabug.dart
pigeons/bug_reporting.api.dart
pigeons/instabug.api.dart
test/bug_reporting_test.dart
test/instabug_test.dart

1. Adds `BugReporting.setDisclaimerText` API
2. Adds `BugReporting.setCommentMinimumCharacterCount` API
3. Deprecates `Instabug.enableAndroid` and `Instabug.disableAndroid` APIs in favour of a new API `Instabug.setEnabled`, which works on both platforms
4. Adds unit tests for the new APIs
**Usage Examples:** 🚀 
1. 
```
BugReporting.setDisclaimerText(
"Instabug can help developers produce more quality code. [Learn more](https://www.instabug.com)"); 
```
2. 
`BugReporting.setCommentMinimumCharacterCount(20);`
Another usage:
```
BugReporting.setCommentMinimumCharacterCount(
20, [ReportType.bug, ReportType.feedback]);
```
3. `Instabug.setEnabled(true);` OR `Instabug.setEnabled(false);`

[MOB-10572] Add new APIs

---

CHANGELOG.md
android/build.gradle

[MOB-10849] Bump Android SDK to `v11.6.0`

---

CHANGELOG.md
README.md
android/src/main/java/com/instabug/flutter/InstabugFlutterPlugin.java
android/src/main/java/com/instabug/flutter/modules/InstabugApi.java
android/src/test/java/com/instabug/flutter/InstabugApiTest.java
e2e/BugReporting.cs
example/android/app/src/androidTest/java/com/example/InstabugSample/InvokeInstabugUITest.java
example/lib/main.dart

When invoking Instabug on Android, a ["scary" dialog](https://github.com/Instabug/Instabug-Flutter/issues/251) appears, asking for permission to record screen. This was due to the way we captured screenshots on Android, using [Media Projection](https://developer.android.com/reference/android/media/projection/MediaProjection), since other alternatives didn't work with Flutter.
This PR aims at providing an alternative approach for Media Projection, using [`FlutterRenderer`](https://api.flutter.dev/javadoc/io/flutter/embedding/engine/renderer/FlutterRenderer.html) to capture screenshots. This implicitly fixes [Repro Steps](https://docs.instabug.com/docs/flutter-repro-steps) on Android as well.

[MOB-10001] Remove Media Projection from Android

---

CHANGELOG.md
android/src/main/java/com/instabug/flutter/InstabugFlutterPlugin.java
android/src/main/java/com/instabug/flutter/modules/CrashReportingApi.java
android/src/main/java/com/instabug/flutter/modules/InstabugApi.java
ios/Classes/Modules/InstabugApi.m

Some APIs forcefully logged some info, even without debug mode enabled. These APIs include:
1. Starting the SDK
1. Crash Reporting APIs on Android
1. All Network logs on iOS
1. Repro Steps screenshots on Android

[MOB-10896] Remove Redundant Native Logs

---

lib/src/models/crash_data.dart
lib/src/models/exception_data.dart
lib/src/models/network_data.dart
lib/src/models/trace.dart
lib/src/modules/apm.dart
lib/src/modules/crash_reporting.dart
lib/src/modules/network_logger.dart
test/apm_test.dart
test/crash_reporting_test.dart
test/network_data_test.dart
test/network_logger_test.dart
test/trace_test.dart

Use the following style across all internal model classes:
```dart
class ModelName {
// 1. Constructor (const if possible)
const ModelName({
required this.firstField,
required this.secondFiled,
});
// 2. Fields
final Type firstField;
final Type secondField;
// 3. Methods
void firstMethod() {
}
// 4. JSON encoding (used with `jsonEncode`)
Map<String, dynamic> toJson() {
return {
'firstField': firstField,
'secondFiled': secondFiled,
};
}
}
```

[MOB-10816] Unify Internal Models Style

---

lib/src/modules/apm.dart
lib/src/modules/bug_reporting.dart
lib/src/modules/crash_reporting.dart
lib/src/modules/feature_requests.dart
lib/src/modules/instabug.dart
lib/src/modules/instabug_log.dart
lib/src/modules/network_logger.dart
lib/src/modules/replies.dart
lib/src/modules/surveys.dart
scripts/pigeon.sh
test/apm_test.dart
test/bug_reporting_test.dart
test/crash_reporting_test.dart
test/feature_requests_test.dart
test/instabug_log_test.dart
test/instabug_test.dart
test/network_logger_test.dart
test/replies_test.dart
test/surveys_test.dart
test/trace_test.dart

After migrating to pigeon in #279, a lot of internal APIs got exposed in the public [API Reference of v11.5.0](https://pub.dev/documentation/instabug_flutter/11.5.0/). This is fixed by:
1. Moving `generated` directory under `src`.
2. Adding `@nodoc` comments to internal methods.

[MOB-10900] Remove Internals from API Reference

---

android/src/main/java/com/instabug/flutter/modules/ApmApi.java
android/src/main/java/com/instabug/flutter/modules/BugReportingApi.java
android/src/main/java/com/instabug/flutter/modules/FeatureRequestsApi.java
android/src/main/java/com/instabug/flutter/modules/InstabugApi.java
android/src/main/java/com/instabug/flutter/util/ArgsRegistry.java
android/src/test/java/com/instabug/flutter/ArgsRegistryTest.java

The two `ArgsRegistry` methods `getDeserializedValue` and `getRawValue` were not type safe at runtime.
This PR provide a type-safe way to achieve enum resolution on Android.

[MOB-10950] Make `ArgsRegistry` Type-safe on Android

---

CHANGELOG.md
android/src/main/java/com/instabug/flutter/modules/InstabugApi.java
ios/Classes/Modules/InstabugApi.m

**Problem:**
If a certain `CustomTextPlaceHolderKey` is mapped only on iOS but not Android, and this key is passed to `setValueForStringWithKey` API, a `NullPointerException` is thrown when running the app on Android. 
**Solution:**
Add a condition to check if the `placeholders` ArgsMap contains this key before getting its value. 

[MOB-10972] Fix `setValueForStringWithKey` null exceptions

---

CHANGELOG.md
android/src/main/java/com/instabug/flutter/util/ArgsRegistry.java
android/src/test/java/com/instabug/flutter/ArgsRegistryTest.java
ios/Classes/Util/ArgsRegistry.m
lib/src/modules/instabug.dart

Add these string keys: `okButtonText`, `audio`, `image`, `screenRecording`, `messagesNotificationAndOthers`, `insufficientContentTitle`, `insufficientContentMessage` with their mapping on both platforms (if relevant).
Note:
This is based on an internal snapshot, so the Android tests are expected to fail until we bump to the Android release including the new keys.
To-Do:
Rebase the PR after bumping the Android version ✅ 

[MOB-10637] Add Overridable String Keys

---

CHANGELOG.md
android/src/main/java/com/instabug/flutter/modules/InstabugApi.java
android/src/main/java/com/instabug/flutter/util/ArgsRegistry.java
android/src/test/java/com/instabug/flutter/InstabugApiTest.java
ios/Classes/Modules/InstabugApi.m
lib/src/modules/apm.dart
lib/src/modules/instabug.dart
pigeons/instabug.api.dart
test/apm_test.dart
test/instabug_test.dart

We had two different native APIs for SDK logs, which were mapped accordingly in Flutter. Since this is now unified natively, this PR does the following:
1. Adds `setSdkDebugLogsLevel` implementation on Android.
2. Deprecates `setDebugEnabled` and updates its implementation to use the new API when called on Android, in addition to the related unit tests.
3. Removes setDebugEnabled from the native bridge.
Note:
This is based on an internal snapshot, so the Android tests are expected to fail until we bump to the Android release, including this API.
To-Do:
Rebase the PR after bumping the Android version

[MOB-10573] Support `setSdkDebugLogsLevel` on Android

---

CHANGELOG.md
android/build.gradle

Allow users to use Instabug Android SDK within their Java/Kotlin files.
[MOB-10607]: https://instabug.atlassian.net/browse/MOB-10607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOB-11799]: https://instabug.atlassian.net/browse/MOB-11799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOB-11812]: https://instabug.atlassian.net/browse/MOB-11812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOB-11811]: https://instabug.atlassian.net/browse/MOB-11811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOB-10650]: https://instabug.atlassian.net/browse/MOB-10650?atlOrigin=eyJpIjoiNWRkNTljNzY …

[MOB-11894] Export Native Android SDK

---

CHANGELOG.md
android/src/main/java/com/instabug/flutter/modules/InstabugApi.java
android/src/main/java/com/instabug/flutter/util/ArgsRegistry.java
android/src/test/java/com/instabug/flutter/ArgsRegistryTest.java
android/src/test/java/com/instabug/flutter/InstabugApiTest.java
example/ios/InstabugSampleTests/InstabugApiTests.m
example/lib/main.dart
ios/Classes/Modules/InstabugApi.m
ios/Classes/Util/ArgsRegistry.h
ios/Classes/Util/ArgsRegistry.m
lib/src/modules/apm.dart
lib/src/modules/instabug.dart
pigeons/instabug.api.dart
test/apm_test.dart
test/instabug_test.dart

A new way to enable SDK debug logs, using the newly added `Instabug.init` API, that works on all platform and for all modules.
```dart
Instabug.setDebugEnabled(true); // Android only
Instabug.setSdkDebugLogsLevel(IBGSDKDebugLogsLevel.error); // iOS only
APM.setLogLevel(LogLevel.error); // APM only
```
```dart
Instabug.init({
// ...
debugLogsLevel: LogLevel.error,
});
```

[MOB-11936] Add `debugLogsLevel` to `Instabug.init`

---

.circleci/config.yml

Migrate `e2e_ios_captain` job's deprecated macOS large resource class machine to the new `macos.x86.medium.gen2`.

[MOB-12204] Upgrade macOS Resource Class to Gen2

---

CHANGELOG.md
example/ios/Podfile.lock
ios/instabug_flutter.podspec

[MOB-12236] Bump iOS SDK to `v11.10.0`

---

CHANGELOG.md
example/ios/Podfile.lock
ios/instabug_flutter.podspec

[MOB-12241] Bump iOS SDK to `v11.10.1`

---

.circleci/config.yml
dangerfile.ts
example/pubspec.lock
package.json
yarn.lock

Integrates the repo with the new Danger code coverage plugin for visibility on code coverage on PRs.

[MOB-12122] Integrate Danger Coverage Plugin

---

.circleci/config.yml
scripts/pigeon.sh

The `flutter format` command has been deprecated in favor of `dart format`.
Change `flutter format` to `dart format`.

[MOB-12372] Migrate Flutter Formatting to Dart

---

CHANGELOG.md
example/ios/Podfile.lock
ios/instabug_flutter.podspec

[MOB-12433] Bump iOS SDK to `v11.12.0`

---

CHANGELOG.md
android/build.gradle

- Bump Android SDK to v11.12.0

[MOB-12434] Bump Android SDK to `v11.12.0`

---

CHANGELOG.md
android/src/main/java/com/instabug/flutter/modules/BugReportingApi.java
android/src/main/java/com/instabug/flutter/util/ThreadManager.java

The `BugReporting.setOnInvokeCallback` API breaks the `Instabug.show` API because the on-invoke doesn't get called on the main thread which causes the native Android SDK to produce the following error:
```
E/IBG-Core(22608): Instabug failed to execute {Instabug.show} due toMethods marked with @UiThread must be executed on the main thread. Current thread: IBG-API-executor-0
```
This PR fixes this issue by running the on-invoke callback for Flutter on the main thread.

[INSD-9704] Fix The `onInvoke` Callback

---

CHANGELOG.md
android/src/main/java/com/instabug/flutter/modules/ApmApi.java
android/src/main/java/com/instabug/flutter/modules/BugReportingApi.java
android/src/main/java/com/instabug/flutter/modules/InstabugApi.java
android/src/main/java/com/instabug/flutter/modules/RepliesApi.java
android/src/main/java/com/instabug/flutter/modules/SurveysApi.java
android/src/test/java/com/instabug/flutter/util/GlobalMocks.java

As stated in the [Flutter docs](https://docs.flutter.dev/platform-integration/platform-channels?tab=type-mappings-kotlin-tab#jumping-to-the-ui-thread-in-android)
> To comply with channels’ UI thread requirement, you might need to jump from a background thread to Android’s UI thread to execute a channel method.
We have some APIs that run on a background thread either explicitly by using `ThreadManager.runOnBackground` or are implicitly called on a background thread by the native Android SDK.
This is the same issue we fixed in #369 for the `onInvoke` callback but applied to all the remaining APIs.
In order to fix this issue, all channel method calls (e.g. sending results, invoking callbacks) have been wrapped with `ThreadManager.runOnMainThread`.

[INSD-9768] Fix Channel Method Calls on Background Threads

---

CHANGELOG.md
android/build.gradle

[MOB-12546] Bump Android SDK to v11.13.0

---

README.md
example/lib/main.dart

Fix zone mismatch issue produced by adding the SDK initialization code in the `main()` function.

[MOB-12516] Fix zone mismatch issue

---

.circleci/config.yml
example/lib/main.dart
ios/Classes/Modules/BugReportingApi.m
ios/Classes/Modules/RepliesApi.m
ios/Classes/Modules/SurveysApi.m
pubspec.yaml
scripts/pigeon.sh

Fix Mockito and Pigeon conflict with flutter_test 

[MOB-12513] Fix Mockito and Pigeon Dependency Conflict

---

CHANGELOG.md
example/ios/Podfile.lock
ios/instabug_flutter.podspec

Bump iOS SDK to 11.14.0
> [MOB-12993](https://instabug.atlassian.net/browse/MOB-12993) -- subtask of --> [MOB-12983](https://instabug.atlassian.net/browse/MOB-12983)
[MOB-12993]: https://instabug.atlassian.net/browse/MOB-12993?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOB-12983]: https://instabug.atlassian.net/browse/MOB-12983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(ios): bump sdk to 11.14.0

---

CHANGELOG.md
ios/Classes/Modules/InstabugApi.m
ios/Classes/Util/IBGNetworkLogger+CP.h
lib/src/modules/network_logger.dart
lib/src/utils/network_manager.dart
test/network_logger_test.dart
test/network_manager_test.dart

Add network logs obfuscation support through the new `NetworkLogger.obfuscateLog` API.
Jira ID: MOB-12523

feat: support network logs obfuscation

---

CHANGELOG.md
android/src/main/java/com/instabug/flutter/modules/InstabugApi.java
android/src/main/java/com/instabug/flutter/util/ArgsRegistry.java
android/src/test/java/com/instabug/flutter/ArgsRegistryTest.java
android/src/test/java/com/instabug/flutter/InstabugApiTest.java
example/ios/InstabugTests/ArgsRegistryTests.m
example/ios/InstabugTests/InstabugApiTests.m
ios/Classes/Modules/InstabugApi.m
ios/Classes/Util/ArgsRegistry.h
ios/Classes/Util/ArgsRegistry.m
lib/src/modules/instabug.dart
pigeons/instabug.api.dart
test/instabug_test.dart

Add support for the new `Instabug.setReproStepsConfig` API and deprecate the old `Instabug.setReproStepsMode`.
Jira ID: MOB-13005

feat: add new repro steps api

---

CHANGELOG.md
example/ios/Podfile.lock
ios/instabug_flutter.podspec

Bump iOS SDK to v12.1.0
Jira ID: [MOB-13044](https://instabug.atlassian.net/browse/MOB-13044)
- #397 
[MOB-13044]: https://instabug.atlassian.net/browse/MOB-13044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(ios): bump sdk 12.1.0

---

CHANGELOG.md
android/build.gradle

Bump android SDK to v1.12.1.0
Jira ID: [MOB-13045](https://instabug.atlassian.net/browse/MOB-13045)
- 
[MOB-13045]: https://instabug.atlassian.net/browse/MOB-13045?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(android): bump sdk 12.1.0

---

android/src/main/java/com/instabug/flutter/modules/InstabugApi.java
android/src/test/java/com/instabug/flutter/ApmApiTest.java
android/src/test/java/com/instabug/flutter/InstabugApiTest.java
example/ios/InstabugTests/ApmApiTests.m
example/ios/InstabugTests/InstabugApiTests.m
ios/Classes/Modules/InstabugApi.m
lib/src/modules/instabug.dart
pigeons/instabug.api.dart
test/instabug_test.dart

- Add session replay mode argument to reprosteps api
- Refactor tests to match the updates
[IBGCRASH-20025](https://instabug.atlassian.net/browse/IBGCRASH-20025)
- #397 
[IBGCRASH-20025]: https://instabug.atlassian.net/browse/IBGCRASH-20025?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add session replay mode argument to reprosteps api

---

CHANGELOG.md
android/src/main/java/com/instabug/flutter/InstabugFlutterPlugin.java
android/src/main/java/com/instabug/flutter/modules/SessionReplayApi.java
android/src/test/java/com/instabug/flutter/SessionReplayApiTest.java
example/ios/InstabugTests/ApmApiTests.m
example/ios/InstabugTests/SessionReplayApiTests.m
example/ios/Runner.xcodeproj/project.pbxproj
ios/Classes/InstabugFlutterPlugin.m
ios/Classes/Modules/SessionReplayApi.h
ios/Classes/Modules/SessionReplayApi.m
lib/instabug_flutter.dart
lib/src/modules/session_replay.dart
pigeons/session_replay.api.dart
test/session_replay_test.dart

- Add new session replay APIs
- Unit test the session replay APIs
- [MOB-13047](https://instabug.atlassian.net/browse/MOB-13047)
- [IBGCRASH-20007](https://instabug.atlassian.net/browse/IBGCRASH-20007)
- #397 
[MOB-13047]: https://instabug.atlassian.net/browse/MOB-13047?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOB-13049]: https://instabug.atlassian.net/browse/MOB-13049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOB-13050]: https://instabug.atlassian.net/browse/MOB-13050?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IBGCRASH-20004]: https://instabug.atlassian.net/browse/IBGCRASH-20004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTR …

feat: add new session replay apis

---

CHANGELOG.md
android/build.gradle

Bump android SDK to `v12.2.0`
Jira ID: [MOB-13243](https://instabug.atlassian.net/browse/MOB-13243)
[MOB-13243]: https://instabug.atlassian.net/browse/MOB-13243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(android): bump sdk to v12.2.0

---

CHANGELOG.md
example/ios/Podfile.lock
ios/instabug_flutter.podspec

Bump iOS SDK to `v12.2.0`
Jira ID: [MOB-13244](https://instabug.atlassian.net/browse/MOB-13244)
[MOB-13244]: https://instabug.atlassian.net/browse/MOB-13244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(ios): bump sdk v12.2.0

---

CHANGELOG.md
lib/src/modules/instabug.dart

Remove unnecessary mapping that mapped ReproStepsMode.enabled to ReproStepsMode.enabledWithNoScreenshots for iOS platform. This workaround was added due to an [issue](https://instabug.atlassian.net/browse/IBGCRASH-19924) with crashes repro steps with screenshots in the iOS SDK, and now it's no longer needed as the issue has been resolved. This re-enabled it for Crash Reporting and Session Replay.
Jira ID: [IBGCRASH-20557](https://instabug.atlassian.net/browse/IBGCRASH-20557)
[IBGCRASH-20557]: https://instabug.atlassian.net/browse/IBGCRASH-20557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ios): enable screenshots for crashes & sessions

---

.circleci/config.yml
scripts/pigeon.sh

`flutter pub run` has been deprecated in favor of `dart run` for some time now, we are migrating to `dart run` instead.
Whenever you use `flutter pub run` you’d get this log if you’re on a newer version of Flutter and Dart.
> Deprecated. Use `dart run` instead.
Jira ID: MOB-13178

chore: use `dart run` instead of `flutter pub run`

---

.circleci/config.yml

- pigeon generation was failing without `dart pub get`
- created a command to run `dart pub get` with `flutter pub get` as well as generate pigeon if `generate_pigeons` is set `true`.
- [\[MOB-13261\] \[CP\] \[FLT\] Fix failing CI for pigeon generation - JIRA](https://instabug.atlassian.net/browse/MOB-13261)

ci: Add `dart pub get` along with `flutter pub get`

---

.circleci/config.yml

fix ci failure due to pubs not being downloaded; utilize `dart pub get`
- [\[MOB-13261\] Fix failing CI for pigeon generation](https://instabug.atlassian.net/browse/MOB-13261)

fix: resolve failure to install pubs using `dart pub get`

---

.circleci/config.yml

- fix ci failure due to pubs not being downloaded; utilize `dart pub get` in release pipeline
- [\[MOB-13261\] Fix failing CI for pigeon generation](https://instabug.atlassian.net/browse/MOB-13261)

ci: add `dart pub get` for release

---

.circleci/config.yml

- fix ci failure due to pubs not being downloaded; utilize `dart pub get` in release pipeline
Jira ID: [\[MOB-13261\] Fix failing CI for pigeon generation](https://instabug.atlassian.net/browse/MOB-13261)

ci: add `dart pub get` for release (#415)

---

CHANGELOG.md
example/ios/Podfile.lock
ios/instabug_flutter.podspec

Bump iOS SDK to `v12.4.0`
Jira ID: MOB-13353

chore(ios): bump sdk to v12.4.0

---

CHANGELOG.md
android/build.gradle

Bump Android SDK to `v12.4.1`
Jira ID: MOB-13352

chore(android): bump android sdk to v12.4.1

---

CHANGELOG.md
android/build.gradle

Bump Instabug Android SDK to v12.5.0
Jira ID: MOB-13518

chore(android): bump sdk to v12.5.0

---

CHANGELOG.md
android/build.gradle

Bump Instabug Android SDK to v12.5.0
Jira ID: MOB-13525

chore(android): bump sdk to v12.5.1

---

CHANGELOG.md
example/ios/Podfile.lock
ios/instabug_flutter.podspec

Bump Instabug iOS SDK to v12.5.0
Jira ID: MOB-13519

chore(ios): bump sdk to v12.5.0

---

CHANGELOG.md

Fix typos in changelog where hyperlink text is missing `v` before `12.5.1` and  `12.4.0`
Jira ID: MOB-13590

docs: fix changelog typos

---

.circleci/config.yml

Migrate CircleCI macOS machines to M1 medium.
Jira ID: MOB-13335

ci: migrate macos machines to m1

---

CHANGELOG.md
android/src/main/java/com/instabug/flutter/modules/InstabugApi.java
android/src/test/java/com/instabug/flutter/InstabugApiTest.java
example/ios/InstabugTests/InstabugApiTests.m
ios/Classes/Modules/InstabugApi.m
lib/src/modules/instabug.dart
pigeons/instabug.api.dart
test/instabug_test.dart

Support user identification by ID in `Instabug.identifyUser`.
Jira ID: MOB-13745

feat: support identify user by id

---

CHANGELOG.md
android/build.gradle

Bump Instabug Android SDK to `v12.7.1` 

chore(android): bump sdk to v12.7.1

---

CHANGELOG.md
android/build.gradle
example/ios/Podfile.lock
ios/instabug_flutter.podspec

Bump Instabug iOS SDK to `v12.7.0`
Jira ID: MOB-13985

chore(ios): bump sdk to v12.7.0

---

.circleci/config.yml

The `release` CI job fails to run after the M1 upgrade because Flutter isn’t compatible with Apple Silicon and we need to install Rosetta 2 to get it to work.
Jira ID: MOB-13988

ci: fix release job by installing rosetta

---

CHANGELOG.md
android/src/main/java/com/instabug/flutter/modules/SessionReplayApi.java
android/src/test/java/com/instabug/flutter/SessionReplayApiTest.java
example/ios/InstabugTests/SessionReplayApiTests.m
example/lib/main.dart
example/pubspec.lock
ios/Classes/Modules/SessionReplayApi.m
lib/src/modules/session_replay.dart
pigeons/session_replay.api.dart
test/session_replay_test.dart

1. Map OnSessionReplayLinkReady API that Retrieves the current session's replay link.
Jira ID = [MOB-14010](https://instabug.atlassian.net/browse/MOB-14010)
[MOB-14010]: https://instabug.atlassian.net/browse/MOB-14010?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add session replay link api

---

.circleci/config.yml
e2e/Utils/CaptainTest.cs

> upgrade android orb from 2.0 to 2.5.0 (latest).
upgrade node orbe from 5.1.0 to 5.2.0 (latest).
upgrade the deprecated android image 2022.04.1 to 2024.01.1-ndk
> MOB-14216

ci: upgrade android orb, node orbe android image

---

lib/src/utils/screen_loading/instabug_capture_screen_loading.dart
lib/src/utils/screen_loading/screen_loading_manager.dart

sanitize the Screen name before reporting to Native and will remove any leading or trailing '/' and replace the Root route name with ROOT_PAGE if it equals '/'

feat: sanitize the Screen name before reporting

---

.circleci/config.yml
android/src/main/java/com/instabug/flutter/modules/ApmApi.java
android/src/test/java/com/instabug/flutter/ApmApiTest.java
example/ios/InstabugTests/ApmApiTests.m
example/ios/Podfile
example/pubspec.yaml
ios/Classes/Modules/ApmApi.m
ios/Classes/Util/NativeUtils/IBGAPM+PrivateAPIs.h
ios/instabug_flutter.podspec
lib/src/modules/apm.dart
lib/src/modules/instabug.dart
lib/src/utils/screen_loading/flags_config.dart
lib/src/utils/screen_loading/instabug_capture_screen_loading.dart
lib/src/utils/screen_loading/screen_loading_manager.dart
pigeons/apm.api.dart
pubspec.yaml
test/apm_test.dart
test/utils/screen_loading/screen_loading_manager_test.dart

Add [isEndScreenLoading] API to APM module which checks for endScreenLoading feature flag in native.
Note: in android the api to the same as [isScreenLoadingEnabled] API.

feat: add isEndScreenLoading API

---

CHANGELOG.md
android/build.gradle

1. bump android SDK to v13.1.1
JIRA ID: MOB-14694

chore(android): bump SDK to v13.1.1

---

CHANGELOG.md
example/ios/Podfile.lock
ios/instabug_flutter.podspec

1. bump  iOS SDk to v13.1.0
JIRA ID: MOB-14696

chore(iOS):  bump sdk to v13.1.0

---

CHANGELOG.md
android/build.gradle
example/ios/Podfile
example/ios/Podfile.lock
example/pubspec.lock
ios/Classes/Modules/CrashReportingApi.m
ios/instabug_flutter.podspec
pubspec.yaml

1. Release:v13.1.1
JIRA ID: MOB-14692

Release:v13.1.1

---

CHANGELOG.md
android/build.gradle

Bump Android SDK to v13.2.0
Jira ID: MOB-14892

chore(android): bump sdk to 13.2.0

---

CHANGELOG.md
example/ios/Podfile.lock
ios/instabug_flutter.podspec

Bump iOS SDK to v13.2.0
Jira ID: MOB-14893

chore(ios): bump sdk to v13.2.0

---

example/pubspec.lock
pubspec.yaml

Upgrade Mockito to include all `5.4.x` to support newer Flutter & Dart versions which require Mockito `5.4.4`.
Jira ID: MOB-14997

chore: upgrade mockito

---

CHANGELOG.md
android/build.gradle

Bump Instabug Android SDK to v13.3.0
Jira ID: MOB-15320

chore(android): bump sdk to v13.3.0

---

CHANGELOG.md
android/build.gradle
example/ios/Podfile.lock
ios/instabug_flutter.podspec

Bump Instabug iOS SDK to v13.3.0.
Jira ID: MOB-15322

chore(ios): bump sdk to v13.3.0

---

e2e/SurveysTests.cs

The "Show Manual Survey" E2E test started to fail due to the over-scrolling causing the "Show Manual Survey" button to not be visible on the screen.
Jira ID: MOB-15324

test: fix show manual survey e2e test

---

CHANGELOG.md
lib/src/utils/instabug_navigator_observer.dart
lib/src/utils/repro_steps_constants.dart
lib/src/utils/screen_loading/screen_loading_manager.dart
lib/src/utils/screen_name_masker.dart
test/utils/instabug_navigator_observer_test.dart

Fallback to "N/A" when a screen with an empty screen name is observed, this prevents crashes in `ScreenLoadingManager` because the screen name is empty and prevents the screen change event from being dropped.
Jira ID: INSD-12170
Fixes #504

fix: use a fallback for empty screen names

---

CHANGELOG.md
android/build.gradle

chore(android): bump sdk to v13.4.1
JIRA ID : MOB-15858

chore(android): bump sdk to v13.4.1

---

CHANGELOG.md
example/ios/Podfile.lock
ios/instabug_flutter.podspec

Bump Instabug iOS SDK to v13.4.1
Jira ID: MOB-15858

chore(ios): bump sdk to v13.4.1

---

CHANGELOG.md

Update changelog for 13.4.0 release.
Jira ID: MOB-15858

chore: update release changelog

---

CHANGELOG.md
example/ios/Podfile.lock
ios/instabug_flutter.podspec

Bump Instabug iOS SDK to v13.4.2
Jira ID: MOB-15858

chore(ios): bump sdk to v13.4.2

---

CHANGELOG.md
android/build.gradle
example/ios/InstabugTests/InstabugApiTests.m
example/ios/Podfile.lock
example/ios/Runner.xcodeproj/project.pbxproj
example/lib/main.dart
example/lib/src/components/network_content.dart
example/pubspec.lock
example/pubspec.yaml
ios/Classes/Modules/InstabugApi.m
ios/Classes/Util/IBGNetworkLogger+CP.h
ios/instabug_flutter.podspec
lib/instabug_flutter.dart
lib/src/models/instabug_route.dart
lib/src/modules/instabug.dart
lib/src/utils/instabug_navigator_observer.dart
lib/src/utils/repro_steps_constants.dart
lib/src/utils/screen_loading/screen_loading_manager.dart
lib/src/utils/screen_loading/ui_trace.dart
lib/src/utils/screen_name_masker.dart
pubspec.yaml
test/instabug_test.dart
test/utils/instabug_navigator_observer_test.dart
test/utils/screen_loading/screen_loading_manager_test.dart
test/utils/screen_name_masker_test.dart

Release: v13.4.0
JIRA ID : MOB-15858

release: v13.4.0

---

example/ios/InstabugTests/PrivateViewApiTests.m
example/ios/Podfile
example/ios/Podfile.lock
example/ios/Runner.xcodeproj/project.pbxproj
example/pubspec.lock
ios/Classes/InstabugFlutterPlugin.m
ios/Classes/Modules/InstabugApi.h
ios/Classes/Modules/InstabugApi.m
ios/Classes/Modules/PrivateViewApi.h
ios/Classes/Modules/PrivateViewApi.m
ios/Classes/Util/FlutterPluginRegistrar+FlutterEngine.h
ios/Classes/Util/FlutterPluginRegistrar+FlutterEngine.m
ios/Classes/Util/Instabug+CP.h

1) implement private views in ios
JIRA ID : MOB-16446

feat(ios): handle private views

---

CHANGELOG.md
android/build.gradle
android/src/main/AndroidManifest.xml
example/android/app/build.gradle
example/android/app/src/debug/AndroidManifest.xml
example/android/app/src/main/AndroidManifest.xml
example/android/app/src/profile/AndroidManifest.xml
example/android/build.gradle
example/android/gradle.properties
example/android/gradle/wrapper/gradle-wrapper.properties
example/ios/Podfile.lock
example/pubspec.lock
example/pubspec.yaml
ios/instabug_flutter.podspec
pubspec.yaml

Release: v14.0.0
JIRA ID: MOB-16651

Release: v14.0.0

---

CHANGELOG.md
android/build.gradle
example/ios/Podfile.lock
example/pubspec.lock
ios/instabug_flutter.podspec
pubspec.yaml

release: 14.1.0
JIRA ID : MOB-17068

Release: 14.1.0

---

.circleci/config.yml
e2e/BugReportingTests.cs
e2e/FeatureRequestsTests.cs
e2e/InstabugTests.cs
e2e/SurveysTests.cs
e2e/Utils/CaptainTest.cs
packages/instabug_flutter/android/build.gradle
packages/instabug_flutter/example/ios/Runner.xcodeproj/project.pbxproj
packages/instabug_flutter/example/lib/main.dart
packages/instabug_private_views/android/src/main/java/com/instabug/instabug_private_views/modules/PrivateViewManager.java
packages/instabug_private_views/example/lib/main.dart
packages/instabug_private_views/example/lib/private_view_page.dart

fix: e2e CI jobs

---

CHANGELOG.md
android/build.gradle
android/src/main/java/com/instabug/flutter/modules/InstabugApi.java
android/src/test/java/com/instabug/flutter/InstabugApiTest.java
example/ios/InstabugTests/InstabugApiTests.m
example/ios/Podfile
example/ios/Podfile.lock
ios/Classes/Modules/InstabugApi.m
ios/instabug_flutter.podspec
lib/src/modules/network_logger.dart
pigeons/instabug.api.dart
test/network_logger_test.dart

> Enable and disbale stop capturing network body API
> https://instabug.atlassian.net/browse/MOB-17625

feat: stop capturing network body

---

android/build.gradle
android/src/main/java/com/instabug/apm/networking/ApmNetworkLoggerHelper.java
android/src/main/java/com/instabug/flutter/modules/ApmApi.java
android/src/test/java/com/instabug/flutter/ApmApiTest.java

Replace APM API that uses reflection by a package private API
Jira ID: APM-22032

refactor: Replace APM API that uses reflection by a package private API

---

CHANGELOG.md
android/src/main/java/com/instabug/flutter/modules/BugReportingApi.java
android/src/main/java/com/instabug/flutter/util/ArgsRegistry.java
android/src/test/java/com/instabug/flutter/BugReportingApiTest.java
example/ios/InstabugTests/BugReportingApiTests.m
ios/Classes/Modules/BugReportingApi.m
ios/Classes/Util/ArgsRegistry.h
ios/Classes/Util/ArgsRegistry.m
lib/src/modules/bug_reporting.dart
pigeons/bug_reporting.api.dart

> support BR adding user consents
> https://instabug.atlassian.net/browse/MOB-18126

feat: support BR adding user consents
