README.md
* Fixes a few errors in the current steps.
* Various changes to make integration steps easier to follow.
=> Updates integration steps

README.md, android/build.gradle, android/src/main/java/com/instabug/instabugflutter/InstabugFlutterPlugin.java, example/lib/main.dart, example/test/main.dart, ios/Classes/InstabugFlutterPlugin.m, ios/instabug_flutter.podspec, lib/instabug_flutter.dart
1) Adds Api Mapping in Both android and ios
2) Adds Api method in flutter
3) Adds Testing for the API method call
4) Updates README with the method name in flutter
5) Updating Native SDKs to Latest Version
=> [Mob 2976] Flutter API: IBGBugReporting invoke

README.md, android/src/main/java/com/instabug/instabugflutter/InstabugFlutterPlugin.java, example/lib/main.dart, example/test/main.dart, ios/Classes/InstabugFlutterPlugin.m, lib/instabug_flutter.dart
1) Adds Api Mapping in Both android and ios
2) Adds Api method in flutter
3) Adds Testing for the API method call
4) Updates README with the method name in flutter
=> [MOB-2971] Flutter API: logUserEventWithName:

README.md, android/src/main/java/com/instabug/instabugflutter/InstabugFlutterPlugin.java, example/lib/main.dart, example/test/main.dart, ios/Classes/InstabugFlutterPlugin.m, lib/instabug_flutter.dart, pubspec.yaml, test/instabug_flutter.dart
*Added APIs*
- `getUserAttributeForKey(String key)`
- `getUserAttributes()`
Move tests from the example app to the library itself.
=> [MOB 2950] [MOB 2966] Flutter API: getUserAttributes getUserAttributeForKey

android/src/main/java/com/instabug/instabugflutter/InstabugFlutterPlugin.java, example/ios/Runner/Info.plist
Add enabling screenshot by media projection on Instabug initialization.
Add the iOS permissions NSMicrophoneUsageDescription and NSPhotoLibraryUsageDescription to the example app.
=> [Mob 3136] Flutter Issue: Android Screenshots

README.md
* Updates the readme to reflect changes to our plan for 1.0
* Separates APIs into sections according to which class they are in
=> Updates APIs in README

CHANGELOG.md
=> 📝 Updates Changelog

example/lib/main.dart, lib/BugReporting.dart, lib/Instabug.dart, lib/InstabugLog.dart, lib/instabug_flutter.dart, test/instabug_flutter_test.dart
Divides the library into modules to be on par with native sides
=> 📝 Dividing into modules

CHANGELOG.md, README.md, android/src/main/java/com/instabug/instabugflutter/InstabugFlutterPlugin.java, example/lib/main.dart, ios/Classes/InstabugFlutterPlugin.m, lib/Instabug.dart, test/instabug_flutter_test.dart
1) Android API Mapping
2) IOS API Mapping
3) Flutter API Mapping
4) Adds tests for new API
5) updates Readme
5) updated Changelog
=> [Mob 3185]: Flutter API: sessionProfilerEnabled

CHANGELOG.md, README.md, android/src/main/java/com/instabug/instabugflutter/InstabugFlutterPlugin.java, example/lib/main.dart, ios/Classes/InstabugFlutterPlugin.m, lib/Instabug.dart, test/instabug_flutter_test.dart
* Android API Mapping
* Changed `setPrimaryColor` and `setSessionProfilerEnabled` to use `NSNumber` instead of `NSString`
=> [Mob 3188] - Flutter API: userData

CHANGELOG.md, README.md, android/src/main/java/com/instabug/instabugflutter/InstabugFlutterPlugin.java, example/lib/main.dart, ios/Classes/InstabugFlutterPlugin.m, lib/Instabug.dart, test/instabug_flutter_test.dart
=> [Mob 3189] - [MOB-3191]: Flutter API: FileAttachments

CHANGELOG.md, README.md, android/src/main/java/com/instabug/instabugflutter/InstabugFlutterPlugin.java, example/lib/main.dart, ios/Classes/InstabugFlutterPlugin.m, lib/Instabug.dart, test/instabug_flutter_test.dart
* Android API Mapping
* iOS API Mapping
=> [Mob 3192] - Flutter API: welcomeMessageMode

CHANGELOG.md, README.md, android/build.gradle, android/src/main/java/com/instabug/instabugflutter/InstabugFlutterPlugin.java, example/lib/main.dart, ios/Classes/InstabugFlutterPlugin.m, ios/instabug_flutter.podspec, lib/Surveys.dart, test/instabug_flutter_test.dart
* Surveys.setEnabled
* setAutoShowingEnabled
* getAvailableSurveys
* setOnShowCallback
* setOnDismissCallback
* setShouldShowWelcomeScreen
* showSurveyIfAvailable
=> [Mob 3202] - [MOB-3208]: Flutter API [Surveys] 

CHANGELOG.md, README.md, android/src/main/java/com/instabug/instabugflutter/InstabugFlutterPlugin.java, example/lib/main.dart, ios/Classes/InstabugFlutterPlugin.m, lib/Surveys.dart, pubspec.yaml, test/instabug_flutter_test.dart
* showSurvey
* hasRespondedToSurvey
I will bump the version after the changes are accepted and start the release process
=> [Mob 3209] - [MOB-32011]: Flutter API [Surveys] 

CHANGELOG.md, README.md, android/src/main/java/com/instabug/instabugflutter/InstabugFlutterPlugin.java, example/lib/main.dart, ios/Classes/InstabugFlutterPlugin.m, lib/BugReporting.dart, lib/Chats.dart, lib/FeatureRequests.dart, lib/Instabug.dart, lib/Replies.dart, lib/Surveys.dart, test/instabug_flutter_test.dart
* setEnabled
* show
* hasChats
* setOnNewReplyReceivedCallback
* getUnreadRepliesCount
* setInAppNotificationsEnabled
* setInAppNotificationSound
=> [Mob 3392] - [MOB-3422]: Flutter API [Replies] 

CHANGELOG.md, README.md, example/lib/main.dart, pubspec.yaml
* Create Sample App to match React Native's Sample App
=> Flutter [Sample App]: Create Flutter Sample App

.circleci/config.yml, example/ios/Runner.xcodeproj/project.pbxproj, example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, example/ios/Runner.xcodeproj/xcshareddata/xcschemes/instabug_flutter_exampleTests.xcscheme
=> Run IOS Unit Tests On CI

.circleci/config.yml
=> 📝 Ci Config Fix

CHANGELOG.md, ios/instabug.podspec, pubspec.yaml
=> 📝 cocoapods fix

CHANGELOG.md, README.md, android/build.gradle, android/src/main/java/com/instabug/instabugflutter/ArgsRegistry.java, android/src/main/java/com/instabug/instabugflutter/InstabugFlutterPlugin.java, example/android/app/src/androidTest/java/com/instabug/instabugflutterexample/InvokeInstabugUITest.java, example/android/app/src/main/java/com/instabug/instabugflutterexample/OnMethodCallTests.java, example/android/app/src/test/java/com/instabug/instabugflutterexample/InstabugFlutterPluginTest.java, example/ios/instabug_flutter_exampleTests/instabug_flutter_exampleTests.m, example/ios/instabug_flutter_exampleUITests/instabug_flutter_exampleUITests.m, example/lib/main.dart, ios/Classes/InstabugFlutterPlugin.m, ios/instabug_flutter.podspec, lib/BugReporting.dart, lib/Chats.dart, lib/Instabug.dart, pubspec.yaml, test/instabug_flutter_test.dart
* Bumped native SDKs to 8.6.1
* Removed deprecated APIs
* Added new enum `question`
=> 💎 Release 8.6

.circleci/config.yml, CHANGELOG.md, android/build.gradle, ios/instabug_flutter.podspec, pubspec.yaml
* Updates native SDK dependencies to 8.7
=> Release 8.7

.circleci/config.yml, release.sh
* Fixing automated release flow CircleCi
=> Fixing CI publish

.circleci/config.yml, CHANGELOG.md, android/build.gradle, android/src/main/java/com/instabug/instabugflutter/ArgsRegistry.java, example/android/app/build.gradle, example/android/app/src/androidTest/java/com/instabug/instabugflutterexample/InvokeInstabugUITest.java, example/android/build.gradle, example/android/gradle.properties, example/android/gradle/wrapper/gradle-wrapper.properties, ios/instabug_flutter.podspec, lib/FeatureRequests.dart, test/instabug_flutter_test.dart
* Bumps native SDKs to v9
* Migrate to androidx
=> Bumping to v9

pubspec.yaml
=> Bump flutter version

pubspec.yaml
=> 💎 Bump version to v9.0.1

CHANGELOG.md, ios/instabug_flutter.podspec, pubspec.yaml
* Bump native IOS SDK to v9.0.6
=> Release 9.0.6

.circleci/config.yml, CHANGELOG.md, android/build.gradle, ios/instabug_flutter.podspec, pubspec.yaml
=> Release 9.1.0

ios/instabug_flutter.podspec
Resolves a warning that shows upon running `pod install` https://github.com/Instabug/Instabug-Flutter/issues/128
=> Update LICENSE path

CHANGELOG.md, android/build.gradle, android/proguard-rules.txt, example/android/app/build.gradle, example/lib/main.dart
- Added Proguard rules to protect Flutter bridge class and method names from getting obfuscated when the `minifyEnabled` flag is set to true. (Fixes these issues: #108, #110, and #123)
- Sample app code format.
=> Add Proguard rules for the Android Plugin

CHANGELOG.md, pubspec.yaml
* Adding dependencies to the pubspec.yaml
=> Adding dependencies

CHANGELOG.md, android/src/main/java/com/instabug/instabugflutter/InstabugFlutterPlugin.java, lib/Instabug.dart
* Mapped both Enable/Disabled APIs on Android
=> Map Enable/Disable APIs on Android

.circleci/config.yml
=> Update CI Paths

InstabugSample/pubspec.yaml
Update the SDK path in the sample app.
=> Update SDK path in the sample app

example/android/app/src/main/kotlin/com/example/InstabugSample/CustomFlutterApplication.java, example/lib/main.dart
- Update sample app token used for the UI automation tests.
=> [MOB-5579] Fix UI Automation Tests

.circleci/config.yml, example/android/app/src/main/kotlin/com/example/InstabugSample/CustomFlutterApplication.java, example/lib/main.dart
- Rollback Xcode version for compatibility with Escape build process.
=> [MOB-5228] Fix CI Release Config

codecov.yml, lib/BugReporting.dart, lib/Replies.dart, lib/Surveys.dart, test/instabug_flutter_test.dart
- Added more test coverage in BugReporting, Surveys, and Replies.
=> [MOB-5592] Increase Test Coverage by 10.52%

CHANGELOG.md, pubspec.yaml
=> Bump version to 9.2.0

.vscode/launch.json, example/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata, example/lib/main.dart
- Add sample app buttons for reporting crashes
=> [MOB-5591] Add crash buttons to the sample app

CHANGELOG.md, android/build.gradle, android/src/main/java/com/instabug/instabugflutter/InstabugFlutterPlugin.java, example/ios/Podfile.lock, example/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata, ios/Classes/InstabugFlutterPlugin.m, ios/instabug_flutter.podspec, lib/utils/platform_manager.dart, pubspec.yaml
- Bumps Instabug native SDKs to v10.8
=> [MOB-5607] Release/10.0

.circleci/config.yml, .gitignore, CHANGELOG.md, android/src/main/java/com/instabug/instabugflutter/InstabugFlutterPlugin.java, example/ios/Podfile.lock, ios/instabug_flutter.podspec, lib/instabug_custom_http_client.dart, pubspec.yaml, test/instabug_flutter_test.dart, test/network_logger_test.dart
* Migrates to Flutter Android embedding v2
* Bumps Instabug native SDKs to v10.9
=> [MOB-5988] Release/10.9.0

.circleci/config.yml
=> [MOB-6010] Upgrade CI Xcode version

CHANGELOG.md, android/build.gradle
=> [MOB-6595] Bump Android SDK to 10.11.1

android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties, example/android/app/build.gradle, example/android/build.gradle, example/android/gradle/wrapper/gradle-wrapper.properties
Uses newer versions of Gradle in both package and example.
=> [MOB-8378] Bump Gradle versions

android/build.gradle
=> [MOB-9123] Bump Android SDK to v11.3.0

.github/pull_request_template.md
- Updated the repo's PR template
=> [MOB-9147] Update PR template

LICENSE
=> [MOB-9320] Update LICENSE

example/ios/Flutter/AppFrameworkInfo.plist, example/ios/Runner.xcodeproj/project.pbxproj, example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
Due to recent changes, thsese files always show up in the change list and we have to ignore them from our commits.
=> [MOB-9936] Update Outdated iOS Config in Example

.circleci/config.yml, pubspec.yaml
- Add `pana` package as a dev dependency for score checking
- Add new job `format_flutter` for code format checking
- Add new job `lint_flutter` for lint checking
- Add new job `verify_pub` for score checking and publish dry-run
- Run CI tests on Flutter 2.10.5
- Format `config.yml` file using YAML formatter
=> [MOB-9398] Add CI Quality Checks

CHANGELOG.md, ios/Classes/InstabugFlutterPlugin.m
Prevent clearing logs on each network log.
=> [MOB-9938] Fix Network Logging on iOS

CHANGELOG.md, android/build.gradle, android/proguard-rules.txt, android/src/main/AndroidManifest.xml, android/src/main/java/com/instabug/flutter/ArgsRegistry.java, android/src/main/java/com/instabug/flutter/InstabugFlutterPlugin.java, android/src/test/java/com/instabug/flutter/ArgsRegistryTest.java, example/android/app/src/androidTest/java/com/example/InstabugSample/InvokeInstabugUITest.java, example/android/app/src/main/kotlin/com/example/InstabugSample/OnMethodCallTests.java, ios/instabug_flutter.podspec, pubspec.yaml
- Update pubspec metadata.
- Rename android package from `com.instabug.instabugFlutter` to `com.instabug.flutter`
- Sync versions between pubspec, gradle and podspec.
- Update podspec metadata.
=> [MOB-9977] Update Plugin Metadata

CHANGELOG.md, android/build.gradle
=> [MOB-9981] Bump Android SDK to `v11.4.1`

CHANGELOG.md, ios/instabug_flutter.podspec
=> [MOB-9982] Bump iOS SDK to `v11.2.0`

CHANGELOG.md, android/build.gradle, ios/instabug_flutter.podspec, pubspec.yaml
=> [MOB-9985] Release v11.2.0

.circleci/config.yml, Gemfile, Gemfile.lock
Run `danger` once in its own job, instead of running it in each `flutter_test_*` jobs.
=> [MOB-10535] Extract Danger CI Job

CHANGELOG.md, ios/instabug_flutter.podspec
=> [MOB-10850] Bump iOS SDK to `v11.5.0`

CHANGELOG.md, android/src/main/java/com/instabug/flutter/util/ArgsRegistry.java, ios/Classes/Util/ArgsRegistry.m, lib/src/modules/instabug.dart
- Adds Romanian locale support
=> [INSD-7895] Add Romanian Locale

android/src/main/java/com/instabug/flutter/modules/InstabugApi.java, example/ios/InstabugSampleTests/InstabugSampleTests.m, ios/Classes/Modules/InstabugApi.h, ios/Classes/Modules/InstabugApi.m, lib/src/modules/instabug.dart, pigeons/instabug.api.dart, test/instabug_test.dart
=> [EP-354] Add Custom Logo API

CHANGELOG.md, android/build.gradle, ios/instabug_flutter.podspec, pubspec.yaml
=> [MOB-10857] Release 11.5.0

android/src/main/java/com/instabug/flutter/modules/InstabugApi.java, android/src/test/java/com/instabug/flutter/ApmApiTest.java, android/src/test/java/com/instabug/flutter/BugReportingApiTest.java, android/src/test/java/com/instabug/flutter/CrashReportingApiTest.java, android/src/test/java/com/instabug/flutter/FeatureRequestsApiTest.java, android/src/test/java/com/instabug/flutter/InstabugApiTest.java, android/src/test/java/com/instabug/flutter/InstabugLogApiTest.java, android/src/test/java/com/instabug/flutter/RepliesApiTest.java, android/src/test/java/com/instabug/flutter/SurveysApiTest.java, android/src/test/java/com/instabug/flutter/util/Callback.java, android/src/test/java/com/instabug/flutter/util/GlobalMocks.java, android/src/test/java/com/instabug/flutter/util/MockReflected.java, android/src/test/java/com/instabug/flutter/util/MockResult.java
=> [MOB-10585] Add More Native Android Tests

CHANGELOG.md, android/build.gradle
=> [MOB-11040] Bump Android SDK to `v11.7.0`

CHANGELOG.md, example/ios/InstabugSampleUITests/BugReportingUITests.m, ios/instabug_flutter.podspec
=> [MOB-11071] Bump iOS SDK to `v11.6.0`

android/src/main/java/com/instabug/flutter/modules/InstabugApi.java, example/ios/InstabugSampleTests/InstabugApiTests.m, example/ios/Podfile, ios/Classes/Modules/InstabugApi.h, ios/Classes/Modules/InstabugApi.m, lib/src/modules/instabug.dart, pigeons/instabug.api.dart, test/instabug_test.dart
=> [EP-351] Add Custom Font API

CHANGELOG.md, android/src/main/java/com/instabug/flutter/modules/InstabugApi.java, android/src/main/java/com/instabug/flutter/util/ArgsRegistry.java, android/src/test/java/com/instabug/flutter/InstabugApiTest.java, ios/Classes/Modules/InstabugApi.m, lib/src/modules/apm.dart, lib/src/modules/instabug.dart, pigeons/instabug.api.dart, test/apm_test.dart, test/instabug_test.dart
This change (#304) is getting reverted in favor of future plans of deprecating `Instabug.setSdkDebugLogsLevel` as well.
[MOB-10896]: https://instabug.atlassian.net/browse/MOB-10896?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOB-10816]: https://instabug.atlassian.net/browse/MOB-10816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOB-10900]: https://instabug.atlassian.net/browse/MOB-10900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOB-10950]: https://instabug.atlassian.net/browse/MOB-10950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOB-10967]: …
=> [MOB-11394] Revert "Support setSdkDebugLogsLevel on Android"

CHANGELOG.md, android/build.gradle, ios/instabug_flutter.podspec, pubspec.yaml
=> [MOB-11467] Release v11.6.0

.circleci/config.yml, e2e/BugReportingTests.cs, e2e/FeatureRequestsTests.cs, e2e/InstabugTests.cs, e2e/SurveysTests.cs, e2e/Utils/CaptainTest.cs, example/lib/main.dart
=> [MOB-10607] Add More Captain E2E Tests

example/pubspec.yaml
- Pin `espresso` to `v0.2.0+5` to fix this [error](https://app.circleci.com/pipelines/github/Instabug/Instabug-Flutter/1906/workflows/418099a7-8bd8-49a5-a76a-0aeece5ada40/jobs/9134?invite=true&invite=true#step-116-134).
=> [MOB-11680] Fix Android UI Tests

pubspec.yaml
Fixes issues related to `analyzer` in Flutter v3.7.0
=> [MOB-11799] Relax pigeon Version Constraint

ios/instabug_flutter.podspec
=> [MOB-11812] Fix Podspec License Path

.circleci/config.yml
=> [MOB-11811] Generate Files in `verify_pub` CI Job

ios/instabug_flutter.podspec
=> [MOB-11697] Bump iOS SDK to `v11.7.0`

CHANGELOG.md, android/build.gradle
=> [MOB-11698] Bump Android SDK to `v11.8.0`

CHANGELOG.md, android/build.gradle
=> [MOB-11947] Bump Android SDK to `v11.9.0`

CHANGELOG.md, ios/instabug_flutter.podspec
=> [MOB-11948] Bump iOS SDK to `v11.9.0`

CHANGELOG.md, android/build.gradle, ios/instabug_flutter.podspec, pubspec.yaml
=> [MOB-11951] Release v11.9.0

.circleci/config.yml
=> [MOB-12047] Migrate to Appium 2

.github/stale.yml
=> [MOB-12066] Run Probot Stale only on Issues

.github/auto-assign-issues.yml, .github/lock.yml
=> [MOB-12212] Remove Unused GitHub Apps

CHANGELOG.md, android/build.gradle
=> [MOB-12233] Bump Android SDK to `v11.11.0`

CHANGELOG.md
In this PR, the new changelog guidelines are applied to the `unreleased` section. We should do the same later on retroactively for the previous releases.
=> [MOB-12035] Apply New Changelog Guidelines

CHANGELOG.md, android/build.gradle, example/ios/Podfile.lock, example/pubspec.lock, ios/instabug_flutter.podspec, pubspec.yaml
=> [MOB-12242] Release `v11.10.1`

CHANGELOG.md, android/build.gradle, example/ios/Podfile.lock, example/pubspec.lock, ios/instabug_flutter.podspec, pubspec.yaml
=> [MOB-12435] Release `v11.12.0`

.circleci/config.yml, CHANGELOG.md, android/build.gradle, dangerfile.ts, example/ios/Podfile.lock, example/pubspec.lock, ios/instabug_flutter.podspec, package.json, pubspec.yaml, scripts/pigeon.sh, yarn.lock
=> [MOB-12435] release/11.12.0

.circleci/config.yml, e2e/Utils/CaptainTest.cs
Use the new Captain config to fix E2E tests issues especially on CI.
Jira ID: MOB-13002
=> test: update captain config

CHANGELOG.md, android/build.gradle
Bump Android SDK to 11.14.0
> [MOB-12992](https://instabug.atlassian.net/browse/MOB-12992) -- subtask of --> [MOB-12983](https://instabug.atlassian.net/browse/MOB-12983)
[MOB-12992]: https://instabug.atlassian.net/browse/MOB-12992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOB-12984]: https://instabug.atlassian.net/browse/MOB-12984?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOB-12983]: https://instabug.atlassian.net/browse/MOB-12983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(android): bump sdk to 11.14.0

CHANGELOG.md, android/build.gradle, example/ios/Podfile.lock, example/pubspec.lock, ios/instabug_flutter.podspec, pubspec.yaml
- Release v11.14.0
- 
-
Jira ID: [MOB-13014](https://instabug.atlassian.net/browse/MOB-13014).
[MOB-13014]: https://instabug.atlassian.net/browse/MOB-13014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: update sdk version to v11.14.0

CHANGELOG.md, android/build.gradle, example/ios/Podfile.lock, example/pubspec.lock, ios/instabug_flutter.podspec, pubspec.yaml
Release v12.1.0
Jira ID: MOB-13144
=> release: v12.1.0

CHANGELOG.md, android/build.gradle, example/ios/Podfile.lock, example/pubspec.lock, ios/instabug_flutter.podspec, pubspec.yaml
Release v12.2.0
Jira ID: [\[MOB-13250\] \[FLT\] Release v12.2.0 - JIRA](https://instabug.atlassian.net/browse/MOB-13250)
[MOB-13250]: https://instabug.atlassian.net/browse/MOB-13250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> release: 12.2.0

CHANGELOG.md
docs: update changelog.md
- Add missing date for v12.1.0.
- Fix compare link of v11.14.0 - v12.1.0.
- [\[MOB-13257\] \[CP\] \[FLT\] Update changelog with missing dates and version comparison links - JIRA](https://instabug.atlassian.net/browse/MOB-13257)
=> docs: update changelog headers for date and compare link fixes

CHANGELOG.md
Fix Changelog date for the `v12.2.0` release
Jira ID: MOB-13399
=> chore: fix 12.2.0 release changelog date

CHANGELOG.md, android/build.gradle, example/ios/Podfile.lock, ios/instabug_flutter.podspec, pubspec.yaml
Release `v12.4.0`
Jira ID: MOB-13351
=> release: 12.4.0

CHANGELOG.md, android/build.gradle, example/ios/Podfile.lock, example/pubspec.lock, ios/instabug_flutter.podspec, pubspec.yaml
Release `v12.5.0`
Jira ID: MOB-13534
=> release: 12.5.0

CHANGELOG.md, android/build.gradle, example/ios/Podfile.lock, example/pubspec.lock, ios/instabug_flutter.podspec, pubspec.yaml
Release `v12.7.0`
Jira ID: MOB-13986
=> release: v12.7.0

CHANGELOG.md, android/build.gradle
Bump Android SDK to v13.0.0
JIRA ID : MOB-14361
=> chore(android): bump sdk to v13.0.0

CHANGELOG.md, android/build.gradle, e2e/Utils/CaptainTest.cs, example/ios/Podfile.lock, ios/instabug_flutter.podspec, pubspec.yaml
Release: v13.0.0
Jira ID : MOB-14181
=> Release: 13.0.0 

.circleci/config.yml
1. change android machine tag version
JIRA ID: MOB-14696
=> ci: change android machine tag version

.circleci/config.yml
> Capture Screen loading time in flutter Apps (Manual Approach)
Jira ID: APM-19229
=> add: SCL manual approach 

.circleci/config.yml, CHANGELOG.md, android/build.gradle, example/ios/Podfile.lock, example/pubspec.lock, ios/instabug_flutter.podspec, pubspec.yaml
Bump the Instabug Flutter SDK version to v13.2.0 and add screen loading support to Changelog.
Jira ID: MOB-14894
=> release: v13.2.0

CHANGELOG.md, android/src/main/java/com/instabug/flutter/modules/ApmApi.java, android/src/test/java/com/instabug/flutter/ApmApiTest.java, android/src/test/java/com/instabug/flutter/util/GlobalMocks.java, android/src/test/java/com/instabug/flutter/util/MockReflected.java
Add W3C External Trace Attributes Placeholder For Android
[JiraID:MOB-14980](https://instabug.atlassian.net/browse/MOB-14980)
=> fix(android): add w3c external trace attributes placeholder

CHANGELOG.md, android/build.gradle, example/ios/Podfile.lock, example/pubspec.lock, ios/instabug_flutter.podspec, pubspec.yaml
Release v13.3.0
Jira ID: MOB-15324
=> release: v13.3.0

e2e/SurveysTests.cs
Sync `dev` with `master` after v13.3.0 release.
=> chore: sync dev with master

pubspec.yaml, test/utils/instabug_navigator_observer_test.dart
Add tests for the `InstabugNavigatorObserver` class.
Jira ID: MOB-15531
=> test: add tests for navigator observer

android/build.gradle, example/pubspec.lock
add namespace dependency required to Support Newer Gradle Versions
[jiraID:INSD-12259
](https://instabug.atlassian.net/browse/INSD-12259)
=> fix: add support for newer gradle versions

CHANGELOG.md
Release: v14.0.0
JIRA ID : MOB-16651
=> Release: v14.0.0

CHANGELOG.md
Release: v14.1.0
JIRA ID : MOB-17068
=> Release: v14.1.0

android/src/main/java/com/instabug/flutter/modules/ApmApi.java, ios/Classes/Modules/ApmApi.m, lib/src/modules/apm.dart
Enhance inline code documentation for APM module
Jira ID: APM-21631
=> Enhance inline code documentation 

lib/src/utils/screen_loading/instabug_capture_screen_loading.dart, lib/src/utils/screen_loading/screen_loading_manager.dart
Enhance inline code comments of APM related classes 
Jira ID: APM-21647
=> Enhance inline code comments of APM related classes 

test/utils/screen_loading/instabug_capture_screen_loading_test.dart, test/utils/screen_loading/screen_loading_trace_test.dart, test/utils/screen_loading/ui_trace_test.dart
Enhance the test coverage for files associated with the APM module.
Jira ID: APM-21650
=> Increase apm test coverage

CHANGELOG.md, android/build.gradle, android/src/main/java/com/instabug/flutter/modules/InstabugApi.java, android/src/test/java/com/instabug/flutter/InstabugApiTest.java, android/src/test/java/com/instabug/flutter/util/GlobalMocks.java, android/src/test/java/com/instabug/flutter/util/MockReflected.java, example/ios/Podfile.lock, example/pubspec.lock, ios/instabug_flutter.podspec, pubspec.yaml
Fix current view always reported as NA in android
[JiraId:INSD-13036
](https://instabug.atlassian.net/browse/INSD-13036)
=> fix android crash current view

android/build.gradle, example/ios/Podfile.lock, example/pubspec.lock, ios/instabug_flutter.podspec, pubspec.yaml
=> Release: 14.3.0

CHANGELOG.md, android/build.gradle, example/ios/Podfile.lock, example/pubspec.lock, ios/instabug_flutter.podspec, pubspec.yaml
=> Release: v14.3.1

example/lib/src/screens/screen_render_page.dart, lib/src/utils/screen_rendering/instabug_screen_render_manager.dart, test/utils/screen_render/instabug_screen_render_manager_test.dart, test/utils/screen_render/instabug_screen_render_manager_test_manual_mocks.dart
update logic in the sample app
=> update logic in the sample app

.circleci/config.yml
ci: fix release pipeline hang
JIRA ID :
=> ci: fix release pipeline hang
